### ISSUE TITLE
'Powerpoint.Application' is invalid class string

### ISSUE THREAD

**Issue by hongweipeng** [jackbrookes/batch-ppt-to-pdf#1]
![20180704105942](https://user-images.githubusercontent.com/7546325/42298245-7dddc01a-8037-11e8-82d2-457d4eaac851.png)

Python version: 3.6.5 ，the error message '无效的类字符串' means 'invalid class string', my pc does not install Microsoft office.I use LibreOffice, does this reason cause the error?

**Comment by jackbrookes** [comment]
Yes Microsoft Powerpoint is required.
